### ISSUE TITLE
`mediabron`: koppeling naar bijhorend informatieobject

### ISSUE THREAD

**Issue by rien333** [Regionaal-Archief-Rivierenland/ORI-XSD#24]
Op dit moment is er geen mogelijkheid een mediabron aan een informatieobject te koppelen. Hier liepen we ook tegen aan tijdens het importeren in MAIS. 

Misschien een goede uitbreiding op ORI, of een issue bij de VNG waard? Ik denk dat we in principe wel ORI conform blijven als we de koppeling naar een informatieobject volledig optioneel maken — dan zijn we simpelweg een superset van ORI.

**Comment by rien333** [comment]
Het simpelste is om dit weer gewoon via IDs te doen, trouwens.

**Comment by rien333** [comment]
Upstream issue: https://github.com/VNG-Realisatie/ODS-Open-Raadsinformatie/issues/100

**Comment by lmasrarsaml** [comment]
Aangepast in XSD met één verschil: verwijzing naar informatieobject gaat niet via `<verwijzingInformatieobject>` maar via `<informatieobjectGegevens>`
